version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run deploy:cicd 
  post_build:
    commands:
      - echo "Start testing"
      - if ./node_modules/.bin/mocha | grep failing; then echo "Testing has failed"; else npm run deploy:prod; fi