version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - ./node_modules/.bin/serverless deploy --stage cicd
  post_build:
    commands:
      - echo "Start testing"
      - |
        if ./node_modules/.bin/mocha | grep failing; then 
          echo "Testing has failed"; 
        else 
          ./node_modules/.bin/serverless deploy --stage prod; 
        fi