service: sls-simple-codepipeline
  
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1  
  deploymentBucket: my-serverless-projects
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync        
      Resource: "arn:aws:lambda:ap-southeast-1:*:*:*"    

functions:
  hello:
    handler: src/handler.hello 